namespace MSUIClient.Net;

// 1.12.1 (client build 5875) opcodes. Values verified against
// benilla-protocol/src/messages/opcode.rs (which cites vmangos). This is the
// working subset for connect + entities + movement + combat; add more from
// opcode.rs as new packets are handled. Note: 1.12 has NO SMSG_HEALTH_UPDATE /
// SMSG_POWER_UPDATE / TIME_SYNC — health, power and stats all arrive as UNIT
// fields in SMSG_UPDATE_OBJECT.
public enum Op : ushort
{
    // --- Administrator world recovery ---
    CMSG_WORLD_TELEPORT          = 0x0008,

    // --- Auth / session ---
    SMSG_AUTH_CHALLENGE          = 0x01EC,
    CMSG_AUTH_SESSION            = 0x01ED,
    SMSG_AUTH_RESPONSE           = 0x01EE,
    SMSG_WARDEN_DATA             = 0x02E6,
    CMSG_PING                    = 0x01DC,
    SMSG_PONG                    = 0x01DD,

    // --- Character select / login ---
    CMSG_CHAR_CREATE             = 0x0036,
    CMSG_CHAR_ENUM               = 0x0037,
    CMSG_CHAR_DELETE             = 0x0038,
    SMSG_CHAR_CREATE             = 0x003A,
    SMSG_CHAR_ENUM               = 0x003B,
    SMSG_CHAR_DELETE             = 0x003C,
    CMSG_PLAYER_LOGIN            = 0x003D,
    SMSG_NEW_WORLD               = 0x003E,
    SMSG_TRANSFER_PENDING        = 0x003F,
    SMSG_TRANSFER_ABORTED        = 0x0040,
    SMSG_CHARACTER_LOGIN_FAILED  = 0x0041,
    SMSG_LOGIN_SETTIMESPEED      = 0x0042,
    SMSG_LOGIN_VERIFY_WORLD      = 0x0236,
    CMSG_SET_ACTIVE_MOVER        = 0x026A,
    CMSG_LOGOUT_REQUEST          = 0x004B,
    SMSG_LOGOUT_RESPONSE         = 0x004C,
    SMSG_LOGOUT_COMPLETE         = 0x004D,
    CMSG_LOGOUT_CANCEL           = 0x004E,
    SMSG_LOGOUT_CANCEL_ACK       = 0x004F,
    SMSG_TRIGGER_CINEMATIC       = 0x00FA,
    CMSG_COMPLETE_CINEMATIC      = 0x00FC,
    SMSG_TUTORIAL_FLAGS          = 0x00FD,
    CMSG_TUTORIAL_FLAG           = 0x00FE,
    CMSG_TUTORIAL_CLEAR          = 0x00FF,
    CMSG_TUTORIAL_RESET          = 0x0100,
    SMSG_GROUP_LIST              = 0x007D,
    CMSG_GROUP_INVITE            = 0x006E,
    SMSG_GROUP_INVITE            = 0x006F,
    CMSG_GROUP_ACCEPT            = 0x0072,
    CMSG_GROUP_DECLINE           = 0x0073,
    SMSG_GROUP_DECLINE           = 0x0074,
    CMSG_GROUP_UNINVITE          = 0x0075,
    CMSG_GROUP_UNINVITE_GUID     = 0x0076,
    SMSG_GROUP_UNINVITE          = 0x0077,
    CMSG_GROUP_SET_LEADER        = 0x0078,
    SMSG_GROUP_SET_LEADER        = 0x0079,
    CMSG_LOOT_METHOD             = 0x007A,
    CMSG_GROUP_DISBAND           = 0x007B,
    SMSG_GROUP_DESTROYED         = 0x007C,
    SMSG_PARTY_MEMBER_STATS      = 0x007E,
    SMSG_PARTY_COMMAND_RESULT    = 0x007F,
    CMSG_JOIN_CHANNEL            = 0x0097,
    CMSG_LEAVE_CHANNEL           = 0x0098,
    SMSG_CHANNEL_NOTIFY          = 0x0099,
    CMSG_CHANNEL_LIST            = 0x009A,
    SMSG_CHANNEL_LIST            = 0x009B,
    CMSG_CHANNEL_PASSWORD        = 0x009C,
    CMSG_CHANNEL_SET_OWNER       = 0x009D,
    CMSG_CHANNEL_OWNER           = 0x009E,
    CMSG_CHANNEL_MODERATOR       = 0x009F,
    CMSG_CHANNEL_UNMODERATOR     = 0x00A0,
    CMSG_CHANNEL_MUTE            = 0x00A1,
    CMSG_CHANNEL_UNMUTE          = 0x00A2,
    CMSG_CHANNEL_INVITE          = 0x00A3,
    CMSG_CHANNEL_KICK            = 0x00A4,
    CMSG_CHANNEL_BAN             = 0x00A5,
    CMSG_CHANNEL_UNBAN           = 0x00A6,
    CMSG_CHANNEL_ANNOUNCEMENTS   = 0x00A7,
    CMSG_CHANNEL_MODERATE        = 0x00A8,
    MSG_MINIMAP_PING             = 0x01D5,
    CMSG_GROUP_CHANGE_SUB_GROUP  = 0x027E,
    CMSG_REQUEST_PARTY_MEMBER_STATS = 0x027F,
    CMSG_GROUP_SWAP_SUB_GROUP    = 0x0280,
    CMSG_GROUP_RAID_CONVERT      = 0x028E,
    CMSG_GROUP_ASSISTANT_LEADER  = 0x028F,
    SMSG_PARTY_MEMBER_STATS_FULL = 0x02F2,
    MSG_RAID_TARGET_UPDATE       = 0x0321,
    MSG_RAID_READY_CHECK         = 0x0322,

    // --- Dungeon / raid lockouts + timers (spec P1) ---
    // The Raid Info window: which instances this character is saved to and the
    // reset countdown per lock. Both requests carry an empty body; RaidInfoWire
    // only parses. Values verified against vmangos Opcodes_1_12_1.h (build 5875).
    CMSG_REQUEST_RAID_INFO       = 0x02CD,   // empty body → SMSG_RAID_INSTANCE_INFO
    SMSG_RAID_INSTANCE_INFO      = 0x02CC,   // u32 count, then rows {mapId, secs, instanceId}
    SMSG_INSTANCE_SAVE_CREATED   = 0x02CB,   // u32(0): "you are now saved"
    SMSG_RAID_INSTANCE_MESSAGE   = 0x02FA,   // u32 type, u32 mapId, u32 secs (reset warning)
    CMSG_RESET_INSTANCES         = 0x031D,   // empty body → SMSG_INSTANCE_RESET(_FAILED)
    SMSG_INSTANCE_RESET          = 0x031E,   // u32 mapId (reset succeeded)
    SMSG_INSTANCE_RESET_FAILED   = 0x031F,   // u32 reason, u32 mapId
    SMSG_UPDATE_LAST_INSTANCE    = 0x0320,   // u32 mapId (one permanent bound map in the ownership snapshot)

    // --- Pet stables (spec P3) ---
    // The stablemaster window. All requests address the NPC by guid; unstable/swap
    // also carry the pet number. Values verified against vmangos (build 5875).
    // CMSG_STABLE_REVIVE_PET (0x0274) is intentionally omitted: its server handler
    // is an empty stub (no-op), so there is nothing to drive.
    MSG_LIST_STABLED_PETS        = 0x026F,   // C: {npcGuid}; S: guid,count,slots,rows
    CMSG_STABLE_PET              = 0x0270,   // {npcGuid} — stable the active pet
    CMSG_UNSTABLE_PET            = 0x0271,   // {npcGuid, petNumber}
    CMSG_BUY_STABLE_SLOT         = 0x0272,   // {npcGuid}
    SMSG_STABLE_RESULT           = 0x0273,   // u8 result code
    CMSG_STABLE_SWAP_PET         = 0x0275,   // {npcGuid, petNumber}
    CMSG_MOVE_WORLDPORT_ACK      = 0x00DC,
    // Benilla/reference spelling retained as a numeric-table alias. The packet
    // is client->server in practice; 1.12's table names it MSG_*.
    MSG_MOVE_WORLDPORT_ACK       = 0x00DC,
    CMSG_ZONEUPDATE              = 0x01F4,
    CMSG_AREATRIGGER             = 0x00B4,
    SMSG_AREA_TRIGGER_MESSAGE    = 0x02B8,
    CMSG_TOGGLE_PVP              = 0x0253,

    // --- Object updates ---
    SMSG_UPDATE_OBJECT           = 0x00A9,
    SMSG_DESTROY_OBJECT          = 0x00AA,
    SMSG_COMPRESSED_UPDATE_OBJECT = 0x01F6,

    // --- Queries ---
    CMSG_NAME_QUERY              = 0x0050,
    SMSG_NAME_QUERY_RESPONSE     = 0x0051,
    CMSG_PET_NAME_QUERY          = 0x0052,
    SMSG_PET_NAME_QUERY_RESPONSE = 0x0053,
    CMSG_WHO                     = 0x0062,
    SMSG_WHO                     = 0x0063,
    CMSG_FRIEND_LIST             = 0x0066,
    SMSG_FRIEND_LIST             = 0x0067,
    SMSG_FRIEND_STATUS           = 0x0068,
    CMSG_ADD_FRIEND              = 0x0069,
    CMSG_DEL_FRIEND              = 0x006A,
    SMSG_IGNORE_LIST             = 0x006B,
    CMSG_ADD_IGNORE              = 0x006C,
    CMSG_DEL_IGNORE              = 0x006D,
    CMSG_CHAT_IGNORED            = 0x0225,
    CMSG_PET_SET_ACTION          = 0x0174,
    CMSG_PET_ACTION              = 0x0175,
    CMSG_PET_UNLEARN = 0x2F0,
    SMSG_PET_UNLEARN_CONFIRM = 0x2F1,
    CMSG_PET_ABANDON             = 0x0176,
    CMSG_PET_RENAME              = 0x0177,
    CMSG_PET_CANCEL_AURA         = 0x026B,
    SMSG_PET_SPELLS              = 0x0179,
    SMSG_PET_MODE                = 0x017A,
    SMSG_PET_CAST_FAILED         = 0x0138,
    SMSG_PET_TAME_FAILURE        = 0x0173,
    SMSG_PET_NAME_INVALID        = 0x0178,
    SMSG_PET_BROKEN              = 0x02AF,
    SMSG_PET_ACTION_FEEDBACK     = 0x02C6,
    SMSG_PET_ACTION_SOUND        = 0x0324,
    CMSG_PET_STOP_ATTACK         = 0x02EA,
    CMSG_PET_SPELL_AUTOCAST      = 0x02F3,
    CMSG_INSPECT                 = 0x0114,
    SMSG_INSPECT                 = 0x0115,
    CMSG_CREATURE_QUERY          = 0x0060,
    SMSG_CREATURE_QUERY_RESPONSE = 0x0061,
    CMSG_GAMEOBJECT_QUERY        = 0x005E,
    SMSG_GAMEOBJECT_QUERY_RESPONSE = 0x005F,
    CMSG_ITEM_QUERY_SINGLE       = 0x0056,
    SMSG_ITEM_QUERY_SINGLE_RESPONSE = 0x0058,
    CMSG_QUEST_QUERY             = 0x005C,
    SMSG_QUEST_QUERY_RESPONSE    = 0x005D,

    // --- NPC gossip (1.12.1 Opcodes_1_12_1.h:380-385) ---
    CMSG_GOSSIP_HELLO             = 0x017B,
    CMSG_GOSSIP_SELECT_OPTION     = 0x017C,
    SMSG_GOSSIP_MESSAGE           = 0x017D,
    SMSG_GOSSIP_COMPLETE          = 0x017E,
    CMSG_NPC_TEXT_QUERY           = 0x017F,
    SMSG_NPC_TEXT_UPDATE          = 0x0180,
    SMSG_GOSSIP_POI               = 0x0224,

    // --- Game objects / readable world pages ---
    CMSG_PAGE_TEXT_QUERY          = 0x005A,
    SMSG_PAGE_TEXT_QUERY_RESPONSE = 0x005B,
    CMSG_GAMEOBJ_USE              = 0x00B1,
    SMSG_GAMEOBJECT_PAGETEXT     = 0x01DF,
    SMSG_GAMEOBJECT_CUSTOM_ANIM   = 0x00B3,
    SMSG_FISH_NOT_HOOKED          = 0x01C8,
    SMSG_FISH_ESCAPED             = 0x01C9,
    SMSG_GAMEOBJECT_DESPAWN_ANIM  = 0x0215,

    // --- Questing ---
    CMSG_QUESTGIVER_STATUS_QUERY   = 0x0182,
    SMSG_QUESTGIVER_STATUS         = 0x0183,
    CMSG_QUESTGIVER_HELLO          = 0x0184,
    SMSG_QUESTGIVER_QUEST_LIST     = 0x0185,
    CMSG_QUESTGIVER_QUERY_QUEST    = 0x0186,
    SMSG_QUESTGIVER_QUEST_DETAILS  = 0x0188,
    CMSG_QUESTGIVER_ACCEPT_QUEST   = 0x0189,
    CMSG_QUESTGIVER_COMPLETE_QUEST = 0x018A,
    SMSG_QUESTGIVER_REQUEST_ITEMS  = 0x018B,
    CMSG_QUESTGIVER_REQUEST_REWARD = 0x018C,
    SMSG_QUESTGIVER_OFFER_REWARD   = 0x018D,
    CMSG_QUESTGIVER_CHOOSE_REWARD  = 0x018E,
    SMSG_QUESTGIVER_QUEST_INVALID  = 0x018F,
    SMSG_QUESTGIVER_QUEST_COMPLETE = 0x0191,
    SMSG_QUESTGIVER_QUEST_FAILED   = 0x0192,
    CMSG_QUESTLOG_SWAP_QUEST       = 0x0193,
    CMSG_QUESTLOG_REMOVE_QUEST     = 0x0194,
    SMSG_QUESTLOG_FULL             = 0x0195,
    SMSG_QUESTUPDATE_FAILED        = 0x0196,
    SMSG_QUESTUPDATE_FAILEDTIMER   = 0x0197,
    SMSG_QUESTUPDATE_COMPLETE      = 0x0198,
    SMSG_QUESTUPDATE_ADD_KILL      = 0x0199,
    SMSG_QUESTUPDATE_ADD_ITEM      = 0x019A,
    CMSG_QUEST_CONFIRM_ACCEPT      = 0x019B,
    CMSG_PUSHQUESTTOPARTY          = 0x019D,
    MSG_QUEST_PUSH_RESULT          = 0x0276,
    SMSG_QUEST_CONFIRM_ACCEPT      = 0x019C,   // escort quests: u32 quest, cstring title, u64 starter
    SMSG_SUMMON_REQUEST            = 0x02AB,   // u64 summoner, u32 zone, u32 timeoutMs
    CMSG_SUMMON_RESPONSE           = 0x02AC,   // u64 summoner (accept); decline sends nothing
    CMSG_SELF_RES                  = 0x02B3,   // empty; server casts PLAYER_SELF_RES_SPELL
    CMSG_LOOT_MASTER_GIVE          = 0x02A3,   // u64 loot, u8 slot, u64 target
    SMSG_LOOT_MASTER_LIST          = 0x02A4,   // u8 count, count × u64 candidate
    SMSG_SERVER_MESSAGE            = 0x0291,   // u32 type, cstring text
    SMSG_ZONE_UNDER_ATTACK         = 0x0254,   // u32 areaId
    SMSG_DEFENSE_MESSAGE           = 0x033B,   // u32 zoneId, u32 len, cstring text
    SMSG_CHAT_RESTRICTED           = 0x02FD,   // empty

    // --- Vendor ---
    CMSG_LIST_INVENTORY           = 0x019E,
    SMSG_LIST_INVENTORY           = 0x019F,
    CMSG_SELL_ITEM                = 0x01A0,
    SMSG_SELL_ITEM                = 0x01A1,
    CMSG_BUY_ITEM                 = 0x01A2,
    CMSG_BUY_ITEM_IN_SLOT         = 0x01A3,
    SMSG_BUY_ITEM                 = 0x01A4,
    SMSG_BUY_FAILED               = 0x01A5,
    CMSG_BUYBACK_ITEM             = 0x0290,
    SMSG_ACCOUNT_DATA_MD5        = 0x0209,
    CMSG_REQUEST_ACCOUNT_DATA    = 0x020A,
    SMSG_UPDATE_ACCOUNT_DATA     = 0x020C,
    CMSG_CHAR_RENAME             = 0x02C7,
    SMSG_CHAR_RENAME             = 0x02C8,
    CMSG_REPAIR_ITEM              = 0x02A8,

    // --- Flightmaster / taxi ---
    SMSG_SHOWTAXINODES            = 0x01A9,
    CMSG_TAXINODE_STATUS_QUERY    = 0x01AA,
    SMSG_TAXINODE_STATUS          = 0x01AB,
    CMSG_TAXIQUERYAVAILABLENODES  = 0x01AC,
    CMSG_ACTIVATETAXI             = 0x01AD,
    SMSG_ACTIVATETAXIREPLY        = 0x01AE,
    SMSG_NEW_TAXI_PATH           = 0x01AF,
    CMSG_ACTIVATETAXIEXPRESS     = 0x0312,

    // --- Trainer ---
    CMSG_TRAINER_LIST             = 0x01B0,
    SMSG_TRAINER_LIST             = 0x01B1,
    CMSG_TRAINER_BUY_SPELL        = 0x01B2,
    SMSG_TRAINER_BUY_SUCCEEDED    = 0x01B3,
    SMSG_TRAINER_BUY_FAILED       = 0x01B4,
    CMSG_BINDER_ACTIVATE          = 0x01B5,
    SMSG_PLAYERBINDERROR          = 0x01B6,
    CMSG_BANKER_ACTIVATE          = 0x01B7,
    SMSG_SHOW_BANK                = 0x01B8,
    CMSG_BUY_BANK_SLOT            = 0x01B9,
    SMSG_BUY_BANK_SLOT_RESULT     = 0x01BA,
    CMSG_AUTOSTORE_BANK_ITEM      = 0x0282,
    CMSG_AUTOBANK_ITEM            = 0x0283,

    // --- Mail ---
    CMSG_SEND_MAIL                = 0x0238,
    SMSG_SEND_MAIL_RESULT         = 0x0239,
    CMSG_GET_MAIL_LIST            = 0x023A,
    SMSG_MAIL_LIST_RESULT         = 0x023B,
    CMSG_ITEM_TEXT_QUERY          = 0x0243,
    SMSG_ITEM_TEXT_QUERY_RESPONSE = 0x0244,
    CMSG_MAIL_TAKE_MONEY          = 0x0245,
    CMSG_MAIL_TAKE_ITEM           = 0x0246,
    CMSG_MAIL_MARK_AS_READ        = 0x0247,
    CMSG_MAIL_RETURN_TO_SENDER    = 0x0248,
    CMSG_MAIL_DELETE              = 0x0249,
    CMSG_MAIL_CREATE_TEXT_ITEM    = 0x024A,
    MSG_QUERY_NEXT_MAIL_TIME      = 0x0284,
    SMSG_RECEIVED_MAIL            = 0x0285,
    CMSG_GMTICKET_CREATE          = 0x0205,
    SMSG_GMTICKET_CREATE          = 0x0206,
    CMSG_GMTICKET_UPDATETEXT      = 0x0207,
    SMSG_GMTICKET_UPDATETEXT      = 0x0208,
    CMSG_GMTICKET_GETTICKET       = 0x0211,
    SMSG_GMTICKET_GETTICKET       = 0x0212,
    CMSG_GMTICKET_DELETETICKET    = 0x0217,
    SMSG_GMTICKET_DELETETICKET    = 0x0218,
    CMSG_GMTICKET_SYSTEMSTATUS    = 0x021A,
    SMSG_GMTICKET_SYSTEMSTATUS    = 0x021B,

    // --- Auction house ---
    MSG_AUCTION_HELLO             = 0x0255,
    CMSG_AUCTION_SELL_ITEM        = 0x0256,
    CMSG_AUCTION_REMOVE_ITEM      = 0x0257,
    CMSG_AUCTION_LIST_ITEMS       = 0x0258,
    CMSG_AUCTION_LIST_OWNER_ITEMS = 0x0259,
    CMSG_AUCTION_PLACE_BID        = 0x025A,
    SMSG_AUCTION_COMMAND_RESULT   = 0x025B,
    SMSG_AUCTION_LIST_RESULT      = 0x025C,
    SMSG_AUCTION_OWNER_LIST_RESULT = 0x025D,
    SMSG_AUCTION_BIDDER_NOTIFICATION = 0x025E,
    SMSG_AUCTION_OWNER_NOTIFICATION = 0x025F,
    CMSG_AUCTION_LIST_BIDDER_ITEMS = 0x0264,
    SMSG_AUCTION_BIDDER_LIST_RESULT = 0x0265,
    SMSG_PVP_CREDIT               = 0x028C,
    SMSG_AUCTION_REMOVED_NOTIFICATION = 0x028D,

    // --- Guild ---
    CMSG_GUILD_QUERY              = 0x0054,
    SMSG_GUILD_QUERY_RESPONSE     = 0x0055,
    CMSG_GUILD_CREATE             = 0x0081,
    CMSG_GUILD_INVITE             = 0x0082,
    SMSG_GUILD_INVITE             = 0x0083,
    CMSG_GUILD_ACCEPT             = 0x0084,
    CMSG_GUILD_DECLINE            = 0x0085,
    SMSG_GUILD_DECLINE            = 0x0086,
    CMSG_GUILD_INFO               = 0x0087,
    SMSG_GUILD_INFO               = 0x0088,
    CMSG_GUILD_ROSTER             = 0x0089,
    SMSG_GUILD_ROSTER             = 0x008A,
    CMSG_GUILD_PROMOTE            = 0x008B,
    CMSG_GUILD_DEMOTE             = 0x008C,
    CMSG_GUILD_LEAVE              = 0x008D,
    CMSG_GUILD_REMOVE             = 0x008E,
    CMSG_GUILD_DISBAND            = 0x008F,
    CMSG_GUILD_LEADER             = 0x0090,
    CMSG_GUILD_MOTD               = 0x0091,
    SMSG_GUILD_EVENT              = 0x0092,
    SMSG_GUILD_COMMAND_RESULT     = 0x0093,
    MSG_SAVE_GUILD_EMBLEM         = 0x01F1,
    SMSG_TABARDVENDOR_ACTIVATE    = 0x01F2,
    CMSG_GUILD_RANK               = 0x0231,
    CMSG_GUILD_ADD_RANK           = 0x0232,
    CMSG_GUILD_DEL_RANK           = 0x0233,
    CMSG_GUILD_SET_PUBLIC_NOTE    = 0x0234,
    CMSG_GUILD_SET_OFFICER_NOTE   = 0x0235,
    CMSG_GUILD_INFO_TEXT          = 0x02FC,

    // --- Talents ---
    CMSG_UNLEARN_TALENTS          = 0x0213,
    CMSG_LEARN_TALENT             = 0x0251,
    MSG_TALENT_WIPE_CONFIRM       = 0x02AA,

    // --- Skills ---
    CMSG_UNLEARN_SKILL            = 0x0202,

    // --- Movement (MSG_* are bidirectional) ---
    MSG_MOVE_START_FORWARD       = 0x00B5,
    MSG_MOVE_START_BACKWARD      = 0x00B6,
    MSG_MOVE_STOP                = 0x00B7,
    MSG_MOVE_START_STRAFE_LEFT   = 0x00B8,
    MSG_MOVE_START_STRAFE_RIGHT  = 0x00B9,
    MSG_MOVE_STOP_STRAFE         = 0x00BA,
    MSG_MOVE_JUMP                = 0x00BB,
    MSG_MOVE_START_TURN_LEFT     = 0x00BC,
    MSG_MOVE_START_TURN_RIGHT    = 0x00BD,
    MSG_MOVE_STOP_TURN           = 0x00BE,
    MSG_MOVE_START_PITCH_UP      = 0x00BF,
    MSG_MOVE_START_PITCH_DOWN    = 0x00C0,
    MSG_MOVE_STOP_PITCH          = 0x00C1,
    MSG_MOVE_SET_RUN_MODE        = 0x00C2,
    MSG_MOVE_SET_WALK_MODE       = 0x00C3,
    MSG_MOVE_FALL_LAND           = 0x00C9,
    MSG_MOVE_START_SWIM          = 0x00CA,
    MSG_MOVE_STOP_SWIM           = 0x00CB,
    MSG_MOVE_SET_RUN_SPEED       = 0x00CD,
    MSG_MOVE_SET_RUN_BACK_SPEED  = 0x00CF,
    MSG_MOVE_SET_WALK_SPEED      = 0x00D1,
    MSG_MOVE_SET_SWIM_SPEED      = 0x00D3,
    MSG_MOVE_SET_SWIM_BACK_SPEED = 0x00D5,
    MSG_MOVE_SET_TURN_RATE       = 0x00D8,
    MSG_MOVE_SET_FACING          = 0x00DA,
    MSG_MOVE_SET_PITCH           = 0x00DB,
    SMSG_MOVE_WATER_WALK        = 0x00DE,
    SMSG_MOVE_LAND_WALK         = 0x00DF,
    MSG_MOVE_ROOT                = 236,
    MSG_MOVE_UNROOT              = 237,
    MSG_MOVE_HOVER               = 247,
    MSG_MOVE_FEATHER_FALL        = 688,
    MSG_MOVE_WATER_WALK          = 689,
    SMSG_SPLINE_MOVE_UNROOT      = 772,
    SMSG_SPLINE_MOVE_FEATHER_FALL = 773,
    SMSG_SPLINE_MOVE_NORMAL_FALL = 774,
    SMSG_SPLINE_MOVE_SET_HOVER   = 775,
    SMSG_SPLINE_MOVE_UNSET_HOVER = 776,
    SMSG_SPLINE_MOVE_WATER_WALK  = 777,
    SMSG_SPLINE_MOVE_LAND_WALK   = 778,
    SMSG_SPLINE_MOVE_SET_RUN_MODE = 781,
    SMSG_SPLINE_MOVE_SET_WALK_MODE = 782,
    SMSG_SPLINE_MOVE_ROOT        = 794,
    MSG_MOVE_HEARTBEAT           = 0x00EE,
    SMSG_MOVE_KNOCK_BACK         = 0x00EF,
    CMSG_MOVE_KNOCK_BACK_ACK     = 0x00F0,
    MSG_MOVE_KNOCK_BACK          = 0x00F1,
    MSG_MOVE_TELEPORT            = 0x00C5,
    MSG_MOVE_TELEPORT_ACK        = 0x00C7,
    SMSG_MONSTER_MOVE            = 0x00DD,
    SMSG_MONSTER_MOVE_TRANSPORT  = 686,
    CMSG_MOVE_SPLINE_DONE        = 0x02C9,
    SMSG_FORCE_RUN_SPEED_CHANGE  = 0x00E2,
    CMSG_FORCE_RUN_SPEED_CHANGE_ACK = 0x00E3,
    SMSG_FORCE_RUN_BACK_SPEED_CHANGE = 0x00E4,
    CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK = 0x00E5,
    SMSG_FORCE_SWIM_SPEED_CHANGE = 0x00E6,
    CMSG_FORCE_SWIM_SPEED_CHANGE_ACK = 0x00E7,
    SMSG_FORCE_MOVE_ROOT         = 0x00E8,
    CMSG_FORCE_MOVE_ROOT_ACK     = 0x00E9,
    SMSG_FORCE_MOVE_UNROOT       = 0x00EA,
    CMSG_FORCE_MOVE_UNROOT_ACK   = 0x00EB,
    SMSG_MOVE_FEATHER_FALL      = 0x00F2,
    SMSG_MOVE_NORMAL_FALL       = 0x00F3,
    SMSG_MOVE_SET_HOVER         = 0x00F4,
    SMSG_MOVE_UNSET_HOVER       = 0x00F5,
    CMSG_MOVE_HOVER_ACK         = 0x00F6,
    CMSG_MOVE_FEATHER_FALL_ACK  = 0x02CF,
    CMSG_MOVE_WATER_WALK_ACK    = 0x02D0,
    SMSG_FORCE_WALK_SPEED_CHANGE = 0x02DA,
    CMSG_FORCE_WALK_SPEED_CHANGE_ACK = 0x02DB,
    SMSG_FORCE_SWIM_BACK_SPEED_CHANGE = 0x02DC,
    CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK = 0x02DD,
    SMSG_FORCE_TURN_RATE_CHANGE = 0x02DE,
    CMSG_FORCE_TURN_RATE_CHANGE_ACK = 0x02DF,
    SMSG_COMPRESSED_MOVES          = 0x02FB,
    SMSG_SPLINE_SET_RUN_SPEED   = 0x02FE,
    SMSG_SPLINE_SET_RUN_BACK_SPEED = 0x02FF,
    SMSG_SPLINE_SET_SWIM_SPEED  = 0x0300,
    SMSG_SPLINE_SET_WALK_SPEED  = 0x0301,
    SMSG_SPLINE_SET_SWIM_BACK_SPEED = 0x0302,
    SMSG_SPLINE_SET_TURN_RATE   = 0x0303,
    CMSG_MOVE_FALL_RESET         = 0x02CA,
    CMSG_MOVE_NOT_ACTIVE_MOVER  = 0x02D1,
    SMSG_CLIENT_CONTROL_UPDATE  = 0x0159,
    CMSG_FAR_SIGHT              = 0x027A,

    // --- Combat / spells ---
    CMSG_SET_SELECTION           = 0x013D,
    CMSG_ATTACKSWING             = 0x0141,
    CMSG_ATTACKSTOP              = 0x0142,
    CMSG_SETSHEATHED             = 0x01E0,
    SMSG_ATTACKSTART             = 0x0143,
    SMSG_ATTACKSTOP              = 0x0144,
    SMSG_ATTACKSWING_NOTINRANGE  = 0x0145,
    SMSG_ATTACKSWING_BADFACING   = 0x0146,
    SMSG_ATTACKSWING_NOTSTANDING = 0x0147,
    SMSG_ATTACKSWING_DEADTARGET  = 0x0148,
    SMSG_ATTACKSWING_CANT_ATTACK = 0x0149,
    SMSG_ATTACKERSTATEUPDATE     = 0x014A,
    SMSG_CANCEL_COMBAT           = 0x014E,
    SMSG_AI_REACTION             = 0x013C,
    SMSG_SPELLHEALLOG            = 0x0150,
    SMSG_SPELLENERGIZELOG        = 0x0151,
    SMSG_LOG_XPGAIN              = 0x01D0,
    SMSG_LEVELUP_INFO            = 0x01D4,
    SMSG_EXPLORATION_EXPERIENCE  = 0x01F8,
    SMSG_ENVIRONMENTALDAMAGELOG  = 0x01FC,
    SMSG_SPELLLOGMISS            = 0x024B,
    SMSG_ENCHANTMENTLOG          = 0x01D7,
    SMSG_SPELLLOGEXECUTE         = 0x024C,
    SMSG_PARTYKILLLOG            = 0x01F5,
    SMSG_DISPEL_FAILED           = 0x0262,
    SMSG_SPELLDISPELLOG           = 0x027B,
    SMSG_SPELLINSTAKILLLOG        = 0x032F,
    SMSG_PROCRESIST             = 0x0260,
    SMSG_SPELLORDAMAGE_IMMUNE    = 0x0263,
    SMSG_FEIGN_DEATH_RESISTED    = 0x02B4,
    SMSG_PERIODICAURALOG         = 0x024E,
    SMSG_SPELLDAMAGESHIELD       = 0x024F,
    SMSG_SPELLNONMELEEDAMAGELOG  = 0x0250,
    CMSG_CAST_SPELL              = 0x012E,
    CMSG_CANCEL_CAST             = 0x012F,
    CMSG_CANCEL_AURA             = 0x0136,
    SMSG_UPDATE_AURA_DURATION    = 0x0137,
    CMSG_CANCEL_CHANNELLING      = 0x013B,
    CMSG_CANCEL_AUTO_REPEAT_SPELL = 0x026D,
    CMSG_SET_ACTION_BUTTON       = 0x0128,
    CMSG_SET_ACTIONBAR_TOGGLES   = 0x02BF,
    CMSG_TOGGLE_HELM             = 0x02B9,
    CMSG_TOGGLE_CLOAK            = 0x02BA,
    CMSG_USE_ITEM                = 0x00AB,
    CMSG_OPEN_ITEM               = 0x00AC,
    CMSG_WRAP_ITEM               = 0x01D3,
    CMSG_REQUEST_PET_INFO        = 0x0279,
    CMSG_BATTLEFIELD_LIST       = 0x023C,
    SMSG_BATTLEFIELD_LIST       = 0x023D,
    CMSG_BATTLEFIELD_STATUS     = 0x02D3,
    SMSG_BATTLEFIELD_STATUS     = 0x02D4,
    CMSG_BATTLEFIELD_PORT       = 0x02D5,
    CMSG_AREA_SPIRIT_HEALER_QUERY = 0x02E2,
    CMSG_AREA_SPIRIT_HEALER_QUEUE = 0x02E3,
    SMSG_AREA_SPIRIT_HEALER_TIME = 0x02E4,
    MSG_PVP_LOG_DATA            = 0x02E0,
    CMSG_LEAVE_BATTLEFIELD      = 0x02E1,
    MSG_BATTLEGROUND_PLAYER_POSITIONS = 0x02E9,
    SMSG_BATTLEGROUND_PLAYER_JOINED = 0x02EC,
    SMSG_BATTLEGROUND_PLAYER_LEFT = 0x02ED,
    SMSG_GROUP_JOINED_BATTLEGROUND = 0x02E8,
    CMSG_BATTLEMASTER_JOIN      = 0x02EE,
    MSG_INSPECT_HONOR_STATS      = 0x02D6,
    CMSG_READ_ITEM               = 0x00AD,
    SMSG_READ_ITEM_OK            = 0x00AE,
    SMSG_READ_ITEM_FAILED        = 0x00AF,
    CMSG_AUTOEQUIP_ITEM          = 0x010A,
    CMSG_AUTOSTORE_BAG_ITEM      = 0x010B,
    CMSG_SWAP_ITEM               = 0x010C,
    CMSG_SWAP_INV_ITEM           = 0x010D,
    CMSG_SPLIT_ITEM              = 0x010E,
    CMSG_DESTROYITEM             = 0x0111,
    CMSG_SET_AMMO                = 0x0268,
    SMSG_CAST_RESULT             = 0x0130,
    SMSG_SPELL_START             = 0x0131,
    SMSG_SPELL_GO                = 0x0132,
    SMSG_SPELL_COOLDOWN          = 0x0134,
    SMSG_ITEM_COOLDOWN           = 0x00B0,
    SMSG_COOLDOWN_EVENT          = 0x0135,
    SMSG_CLEAR_COOLDOWN          = 0x01DE,
    SMSG_COOLDOWN_CHEAT          = 0x01E1,
    MSG_CHANNEL_START            = 0x0139,
    MSG_CHANNEL_UPDATE           = 0x013A,
    SMSG_SPELL_DELAYED           = 0x01E2,
    SMSG_UPDATE_INSTANCE_OWNERSHIP = 0x032B,
    SMSG_RAID_GROUP_ONLY         = 0x0286,
    SMSG_INVALIDATE_PLAYER      = 0x031C,
    SMSG_OPEN_CONTAINER          = 0x0113,
    SMSG_ITEM_TIME_UPDATE        = 0x01EA,
    SMSG_ITEM_ENCHANT_TIME_UPDATE = 0x01EB,
    SMSG_SPELL_FAILED_OTHER      = 0x02A6,
    SMSG_PLAY_SPELL_VISUAL       = 0x01F3,
    SMSG_CANCEL_AUTO_REPEAT      = 0x029C,
    SMSG_SPELL_UPDATE_CHAIN_TARGETS = 0x0330,

    // --- Death / resurrection ---
    CMSG_REPOP_REQUEST           = 0x015A,
    SMSG_RESURRECT_REQUEST       = 0x015B,
    CMSG_RESURRECT_RESPONSE      = 0x015C,
    CMSG_RECLAIM_CORPSE          = 0x01D2,
    CMSG_SPIRIT_HEALER_ACTIVATE  = 0x021C,
    MSG_CORPSE_QUERY             = 0x0216,
    SMSG_SPIRIT_HEALER_CONFIRM   = 0x0222,
    SMSG_CORPSE_RECLAIM_DELAY    = 0x0269,
    SMSG_DURABILITY_DAMAGE_DEATH = 0x02BD,

    // --- Server-authoritative breath / fatigue / feign-death bars ---
    SMSG_START_MIRROR_TIMER      = 0x01D9,
    SMSG_PAUSE_MIRROR_TIMER      = 0x01DA,
    SMSG_STOP_MIRROR_TIMER       = 0x01DB,

    // --- Loot (solo corpse loot + group-roll families; values verified against
    //     vmangos Opcodes_1_12_1.h through current benilla-protocol) ---
    CMSG_AUTOSTORE_LOOT_ITEM     = 0x0108,
    CMSG_LOOT                    = 0x015D,
    CMSG_LOOT_MONEY              = 0x015E,
    CMSG_LOOT_RELEASE            = 0x015F,
    SMSG_LOOT_RESPONSE           = 0x0160,
    SMSG_LOOT_RELEASE_RESPONSE   = 0x0161,
    SMSG_LOOT_REMOVED            = 0x0162,
    SMSG_LOOT_MONEY_NOTIFY       = 0x0163,
    SMSG_LOOT_CLEAR_MONEY        = 0x0165,
    SMSG_ITEM_PUSH_RESULT        = 0x0166,
    SMSG_DUEL_REQUESTED          = 0x0167,
    SMSG_DUEL_OUTOFBOUNDS        = 0x0168,
    SMSG_DUEL_INBOUNDS           = 0x0169,
    SMSG_DUEL_COMPLETE           = 0x016A,
    SMSG_DUEL_WINNER             = 0x016B,
    CMSG_DUEL_ACCEPTED           = 0x016C,
    CMSG_DUEL_CANCELLED          = 0x016D,
    SMSG_INVENTORY_CHANGE_FAILURE = 0x0112,
    SMSG_MOUNTRESULT             = 0x016E,
    SMSG_DISMOUNTRESULT          = 0x016F,
    CMSG_MOUNTSPECIAL_ANIM       = 0x0171,
    SMSG_MOUNTSPECIAL_ANIM       = 0x0172,
    SMSG_LOOT_ALL_PASSED         = 0x029E,
    SMSG_LOOT_ROLL_WON           = 0x029F,
    CMSG_LOOT_ROLL               = 0x02A0,
    SMSG_LOOT_START_ROLL         = 0x02A1,
    SMSG_LOOT_ROLL               = 0x02A2,
    SMSG_DUEL_COUNTDOWN          = 0x02B7,

    // --- Misc world state seen at login (parsed leniently / ignored for now) ---
    SMSG_INITIAL_SPELLS          = 0x012A,
    SMSG_ACTION_BUTTONS          = 0x0129,
    SMSG_LEARNED_SPELL           = 0x012B,
    SMSG_SUPERCEDED_SPELL        = 0x012C,
    SMSG_REMOVED_SPELL           = 0x0203,
    SMSG_SET_FACTION_ATWAR      = 787,
    SMSG_SET_FORCED_REACTIONS   = 677,
    SMSG_INITIALIZE_FACTIONS     = 0x0122,
    SMSG_SET_FACTION_VISIBLE     = 0x0123,
    SMSG_SET_FACTION_STANDING    = 0x0124,
    CMSG_SET_FACTION_ATWAR       = 0x0125,
    CMSG_SET_FACTION_INACTIVE    = 0x0317,
    CMSG_SET_WATCHED_FACTION     = 0x0318,
    SMSG_SET_FLAT_SPELL_MODIFIER = 0x0266,
    SMSG_SET_PCT_SPELL_MODIFIER = 0x0267,
    SMSG_SET_PROFICIENCY         = 0x0127,
    // --- Server-scripted world audio ---
    SMSG_PLAY_MUSIC              = 0x0277,
    SMSG_PLAY_OBJECT_SOUND       = 0x0278,
    SMSG_PLAY_SOUND              = 0x02D2,
    SMSG_WEATHER                 = 0x02F4,
    CMSG_INITIATE_TRADE          = 0x0116,
    CMSG_BEGIN_TRADE             = 0x0117,
    CMSG_BUSY_TRADE              = 0x0118,
    CMSG_IGNORE_TRADE            = 0x0119,
    CMSG_ACCEPT_TRADE            = 0x011A,
    CMSG_UNACCEPT_TRADE          = 0x011B,
    CMSG_CANCEL_TRADE            = 0x011C,
    CMSG_SET_TRADE_ITEM          = 0x011D,
    CMSG_CLEAR_TRADE_ITEM        = 0x011E,
    CMSG_SET_TRADE_GOLD          = 0x011F,
    SMSG_TRADE_STATUS            = 0x0120,
    SMSG_TRADE_STATUS_EXTENDED   = 0x0121,
    SMSG_BINDPOINTUPDATE         = 0x0155,
    SMSG_PLAYERBOUND             = 0x0158,
    SMSG_BINDER_CONFIRM          = 0x02EB,
    SMSG_INIT_WORLD_STATES       = 0x02C2,
    SMSG_UPDATE_WORLD_STATE      = 0x02C3,
    CMSG_MESSAGECHAT             = 0x0095,
    SMSG_MESSAGECHAT             = 0x0096,
    CMSG_PLAYED_TIME             = 0x01CC,
    SMSG_PLAYED_TIME             = 0x01CD,
    SMSG_PLAY_TIME_WARNING       = 0x02F5,
    SMSG_PLAYER_SKINNED          = 0x02BC,
    CMSG_QUERY_TIME              = 0x01CE,
    SMSG_QUERY_TIME_RESPONSE     = 0x01CF,
    MSG_RANDOM_ROLL              = 0x01FB,
    SMSG_CHAT_WRONG_FACTION      = 0x0219,
    SMSG_CHAT_PLAYER_NOT_FOUND   = 0x02A9,
    SMSG_NOTIFICATION            = 0x01CB,
    // Confirmed via vmangos/core (WorldSession::HandleStandStateChangeOpcode,
    // Handlers/MiscHandler.cpp; the numeric value from its own
    // Opcodes_1_12_1.h). That same header's CMSG_EMOTE/SMSG_EMOTE/
    // CMSG_TEXT_EMOTE/SMSG_TEXT_EMOTE entries land exactly on this project's
    // own long-confirmed 0x0102-0x0105 values, so the adjacent 0x0101 here
    // carries that same cross-checked confidence, not a fresh guess.
    CMSG_STANDSTATECHANGE        = 0x0101,
    SMSG_STANDSTATE_UPDATE       = 0x029D,
    SMSG_EMOTE                   = 0x0103,
    // Not directly confirmed by the wiki's C++ index (Misc.h's TextEmote gave the
    // struct fields but not the enum value) - standard across every 1.12 server
    // fork (mangos/cmangos/vmangos/TC-classic), all reverse-engineered against the
    // same client binary, and it's the one open slot between its two confirmed
    // neighbours. Empirically verify by sending a text emote in-game.
    CMSG_TEXT_EMOTE              = 0x0104,
    SMSG_TEXT_EMOTE              = 0x0105,

    // --- SuperUI CRPG/RTS control extension (SuperUI-Core fork only; above the
    // vanilla table; values are shared with the matching server extension) ---
    CMSG_SUI_CONTROL_REQUEST     = 0x033C,
    CMSG_SUI_CONTROL_RELEASE     = 0x033D,
    CMSG_SUI_ORDER               = 0x033E,
    SMSG_SUI_CONTROL_ROSTER      = 0x033F,
    SMSG_SUI_CONTROL_ACK         = 0x0340,
    SMSG_SUI_PROXY               = 0x0341,
    SMSG_SUI_SNAPSHOT            = 0x0342,
    CMSG_SUI_CAM                 = 0x0343,
    CMSG_SUI_ZONE_INTEL          = 0x0344,
    SMSG_SUI_ZONE_INTEL          = 0x0345,
    CMSG_SUI_RTS_STATE           = 0x0346,
    SMSG_SUI_RTS_STATE           = 0x0347,
    CMSG_SUI_RTS_ACTION          = 0x0348,
    SMSG_SUI_RTS_ACTION_RESULT   = 0x0349,
    CMSG_SUI_FORCE_ROSTER        = 0x034A,
    SMSG_SUI_FORCE_ROSTER        = 0x034B,

    // REAL_PORTALS starts at the next audited four-opcode block so the two
    // independently developed feature lines can merge without renumbering.
    CMSG_SUI_PORTAL_PREPARE      = 0x034C,
    SMSG_SUI_PORTAL_DESCRIPTOR   = 0x034D,
    CMSG_SUI_PORTAL_READY        = 0x034E,
    SMSG_SUI_PORTAL_STATE        = 0x034F,

    // 0x0350/0x0351 (848/849) are reserved for the dynamic-combat rotation pair;
    // PARTY_MEMBER_FACTS therefore starts one audited pair later.
    CMSG_SUI_MEMBER_FACTS        = 0x0352,
    SMSG_SUI_MEMBER_SPELLS       = 0x0353,
    CMSG_SUI_MEMBER_ITEM_MOVE    = 0x0354,
    SMSG_SUI_MEMBER_ITEM_MOVE_RESULT = 0x0355,

    // PLAN_20 party questing & vendoring. P1 claims the facts pair; 0x0358-0x035B
    // are RESERVED here rather than left blank so the later phases (quest acts,
    // vendor) cannot be renumbered out from under a half-deployed server.
    CMSG_SUI_QUEST_FACTS         = 0x0356,
    SMSG_SUI_QUEST_LOG           = 0x0357,
    CMSG_SUI_PARTY_QUEST         = 0x0358,
    SMSG_SUI_PARTY_QUEST_RESULT  = 0x0359,
    // CMSG_SUI_PARTY_VENDOR     = 0x035A,   (P4)
    // SMSG_SUI_PARTY_VENDOR_RESULT = 0x035B,(P4)
    // P5 lands before P4 but does NOT take P4's numbers: 0x035A/0x035B are named
    // in the plan and reserved on the server, and renumbering a frozen wire to
    // save two indices is how a client and a core quietly stop agreeing.
    CMSG_SUI_GIVER_STATUS        = 0x035C,
    SMSG_SUI_GIVER_STATUS        = 0x035D,
    // P4a. 0x035A/0x035B stay reserved: the owner has narrowed P4's vendor slice
    // but not abandoned it, and re-using a pair a live design still names is the
    // ambiguity the P5 note above exists to avoid.
    CMSG_SUI_PARTY_LEAD          = 0x035E,
    SMSG_SUI_PARTY_LEAD_RESULT   = 0x035F,
    CMSG_SUI_GIVER_QUESTS        = 0x0360,   // Model B: a giver's quests + per-member eligibility
    SMSG_SUI_GIVER_QUESTS        = 0x0361,
    // COMPANIONS v1 (capability bit 7): summon/dismiss the account's own alts as
    // AI party members. CMSG body: u8 action (1 summon, 2 dismiss, 3 list), u64 guid.
    // SMSG body: u8 kind (1 result, 2 list) + payload — see Net/CompanionWire.cs.
    CMSG_SUI_COMPANION           = 0x0362,
    SMSG_SUI_COMPANION           = 0x0363,
    // PARTY_TAXI v1 (capability bit 11): the Command View flies the whole commanded
    // party from a flight master, asking first when someone cannot board.
    // CMSG body: u8 flags, u64 flight master, u8 count, u32 × nodes.
    // SMSG body: u8 result, u64 flight master, u32 destination, u8 count,
    // count × { u64 guid, u8 reason } — see Net/PartyTaxiWire.cs.
    CMSG_SUI_PARTY_TAXI          = 0x0364,
    SMSG_SUI_PARTY_TAXI_RESULT   = 0x0365,
    // TACTICAL_FREEZE v1 (capability bit 12): an explicit Command View button owns a
    // localized server lock; Command View itself remains live. Queue packets carry the
    // KOTOR-style per-actor plans authored while the lock is active.
    CMSG_SUI_COMMANDER_RAID      = 0x036A, // capability 13
    SMSG_SUI_COMMANDER_RAID      = 0x036B,
    CMSG_SUI_THREAT              = 0x036C, // capability 14, ThreatMeterWire
    SMSG_SUI_THREAT              = 0x036D,
    CMSG_SUI_TACTICAL_FREEZE      = 0x0366, // decimal 870
    SMSG_SUI_TACTICAL_FREEZE      = 0x0367, // decimal 871
    CMSG_SUI_TACTICAL_QUEUE       = 0x0368, // decimal 872
    SMSG_SUI_TACTICAL_QUEUE       = 0x0369, // decimal 873
}
