# Generates the `wow-karting` World Content Pack content (shared_docs/WOW_KARTING.md) from course.json:
# kart mount spells, one public Real Portal per course leg (teleport spell + spell_target_position +
# gameobject_template + spawn), laid track (ramps, cleared lanes), the race course (game_tele rows the Core
# race reads), the race marshal, and the MK64 items (effect spells, item box / banana / fake box objects,
# shell creatures) as /WorldPacks/Content batches.
#
#   python tools/worldpack/examples/karting/gen-karting.py OUTDIR            # write the batches (JSON) only
#   python tools/worldpack/examples/karting/gen-karting.py OUTDIR --post     # ... and post them to the web app
#
# Stock source rows are read from the box (ssh 192.168.0.2, world DB, SELECT only) and cloned field for field;
# the client Spell.dbc rows are clones of the same stock rows (WorldPacks\Spell.dbc, rows only - see
# WorldPackContent.RowsOnlyDbcs). Ids: spells 38000+ (karts) / 38100+ (portal teleports) / 38200+ (item effects),
# templates 7,100,000+, spawn guids 1,700,000+, game_tele 7400+ (the pack law: WorldPackContent).
# --post keeps the pack EXACTLY what this generates: docs the course no longer produces are deleted.
import json, math, os, subprocess, sys, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.environ.get("MSUI_WEB", "http://192.168.0.2:5000")
PACK_KEY = "wow-karting"

KART_MARKER = 0x4B415254          # SuiKarting::KART_MARKER: SPELL_AURA_DUMMY misc value = 'KART'
KART_SPEED_PCT = 200              # +200 % mounted speed = 3x run = 21 yd/s (owner, 2026-10-04)
KARTS = [
    # spell, creature (aura 78 misc -> display), name, icon (SpellIcon.dbc)
    (38001, 4251, "Goblin Racer", 1733),   # display 10318 GoblinRocketCar, INV_Gizmo_GoblinBoomBox_01
    (38002, 4252, "Gnome Racer", 1240),    # display 2490 GnomeRocketCar, Ability_Mount_MechaStrider
    (38003, 7_100_020, "Racing Kart", 1733),  # the custom go-kart (kart-model.py), display 71000
]

# The custom go-kart (owner 2026-10-04: "a custom mount (cart) more mario kart / go kart inspired that fits the
# WoW universe"): its M2 is generated by kart-model.py and shipped as a pack asset, with its own
# CreatureModelData / CreatureDisplayInfo rows cloned from the Goblin Racer's (model 1471, display 10318).
KART_MODEL_PATH = "Creature\\SUIKart\\SUIKart.m2"
KART_MODEL_ID = 7_100
KART_DISPLAY_ID = 71_000
KART_CREATURE = 7_100_020
KART_CREATURE_SOURCE = 4251
MOUNT_SOURCE = 23219              # Swift Mistsaber: a stock 100 % mount, cloned field for field
PORTAL_SOURCE_SPELL = 17334       # Portal Effect: Stormwind (TELEPORT_UNITS -> spell_target_position)
PORTAL_SOURCE_GO = 176296         # Portal to Stormwind (type 22, display 4396)
PORTAL_SPELL_BASE = 38100
PORTAL_TEMPLATE_BASE = 7_100_100
PORTAL_GUID_BASE = 1_700_100

# Spell.dbc (build 5875) columns
DBC_CAST_TIME, DBC_EFFECT, DBC_DIE_SIDES, DBC_BASE_POINTS, DBC_TARGET_A = 18, 61, 64, 76, 82
DBC_AURA, DBC_MISC, DBC_ICON, DBC_NAME, DBC_DESC, DBC_AURA_DESC = 91, 106, 117, 120, 138, 147
DBC_ATTRIBUTES = 6
SPELL_ATTR_ONLY_OUTDOORS = 0x00008000


def box_rows(sql):
    """SELECT on the box's world DB -> list of dicts (strings; NULL -> None)."""
    out = subprocess.run(["ssh", "-o", "BatchMode=yes", "wowvmangos@192.168.0.2",
                          f"mysql -umangos -pmangos mangos --batch -e \"{sql}\""],
                         capture_output=True, text=True, check=True).stdout
    lines = [l for l in out.split("\n") if l]
    head = lines[0].split("\t")
    return [{k: (None if v == "NULL" else v) for k, v in zip(head, l.split("\t"))} for l in lines[1:]]


def typed(row):
    """Numbers as JSON numbers so the dbrow writer binds them as numbers."""
    out = {}
    for k, v in row.items():
        if v is None:
            out[k] = None
            continue
        try:
            out[k] = int(v)
        except ValueError:
            try:
                out[k] = float(v)
            except ValueError:
                out[k] = v
    return out


def height(mapid, x, y):
    url = f"{WEB}/WorldMap/GetHeight?map={mapid}&x={x}&y={y}"
    z = json.load(urllib.request.urlopen(url, timeout=30)).get("z")
    if z is None:
        raise SystemExit(f"no terrain height at map {mapid} ({x}, {y})")
    return float(z)


def leg_z(leg, x, y):
    """Ground height for a point on LEG: a route written [x, y, z] (rooftops, city walls - surfaces the server's
    terrain-only height query cannot see) is interpolated along its nearest segment; otherwise the terrain."""
    route = leg["route"]
    if not all(len(q) > 2 for q in route):
        return height(leg["map"], x, y)
    best = None
    for k in range(len(route) - 1):
        (ax, ay, az), (bx, by, bz) = route[k][:3], route[k + 1][:3]
        dx, dy = bx - ax, by - ay
        t = max(0.0, min(1.0, ((x - ax) * dx + (y - ay) * dy) / (dx * dx + dy * dy or 1e-9)))
        d = math.dist((x, y), (ax + dx * t, ay + dy * t))
        if best is None or d < best[0]:
            best = (d, az + (bz - az) * t)
    return best[1]


def row(table, body):
    return {"kind": f"dbrow:{table}", "body": body}


def dbc(name, rid, clone, fields):
    return {"kind": f"dbc:{name}", "key": str(rid), "body": {"cloneFrom": clone, "fields": fields}}


def length(route):
    return sum(math.dist(route[i][:2], route[i + 1][:2]) for i in range(len(route) - 1))


# -- karts ---------------------------------------------------------------------------------------

def kart_items(mount):
    items = []
    for spell, creature, name, icon in KARTS:
        r = dict(mount)
        r.update({
            "entry": spell, "build": 5875, "name": name, "nameSubtext": "",
            "description": f"Summons and dismisses a {name} kart. Karts are very fast, and hostile creatures ignore their drivers.",
            "auraDescription": "Increases speed by $s2%. Hostile creatures ignore you.",
            "castingTimeIndex": 1, "spellIconId": icon,
            # Not outdoors-only: Stormwind's rooftops count as INDOORS (city WMO), and the server strips
            # SPELL_ATTR_ONLY_OUTDOORS auras indoors - the kart vanished on the first roof (2026-10-04).
            "attributes": mount["attributes"] & ~SPELL_ATTR_ONLY_OUTDOORS,
            "effectMiscValue1": creature, "effectBasePoints2": KART_SPEED_PCT - 1,
            "effect3": 6, "effectApplyAuraName3": 4, "effectMiscValue3": KART_MARKER,
            "effectImplicitTargetA3": 1, "effectImplicitTargetB3": 0, "effectDieSides3": 1, "effectBasePoints3": 0,
        })
        items.append(row("spell_template", r))
        items.append(dbc("Spell", spell, MOUNT_SOURCE, {
            str(DBC_NAME): name,
            str(DBC_DESC): r["description"], str(DBC_AURA_DESC): r["auraDescription"],
            str(DBC_CAST_TIME): 1, str(DBC_ICON): icon,
            str(DBC_ATTRIBUTES): mount["attributes"] & ~SPELL_ATTR_ONLY_OUTDOORS,
            str(DBC_MISC): creature, str(DBC_BASE_POINTS + 1): KART_SPEED_PCT - 1,
            str(DBC_EFFECT + 2): 6, str(DBC_AURA + 2): 4, str(DBC_MISC + 2): KART_MARKER,
            str(DBC_TARGET_A + 2): 1, str(DBC_DIE_SIDES + 2): 1,
        }))
    return items


def kart_model_items():
    import base64, subprocess, tempfile
    out = os.path.join(tempfile.gettempdir(), "SUIKart.m2")
    subprocess.run([sys.executable, os.path.join(HERE, "kart-model.py"), out], check=True)
    model = open(out, "rb").read()
    tread = open(os.path.join(os.path.dirname(out), "SUIKartTread.blp"), "rb").read()
    t = typed(box_rows(f"SELECT * FROM creature_template WHERE entry={KART_CREATURE_SOURCE} ORDER BY patch DESC LIMIT 1")[0])
    t.update({"entry": KART_CREATURE, "patch": 0, "name": "Racing Kart", "subname": "", "display_id1": KART_DISPLAY_ID,
              "display_id2": 0, "display_id3": 0, "display_id4": 0, "display_scale1": 1, "display_probability1": 100,
              "display_total_probability": 100, "ai_name": "", "script_name": ""})
    return [
        {"kind": "asset", "key": KART_MODEL_PATH, "body": {"base64": base64.b64encode(model).decode("ascii")}},
        {"kind": "asset", "key": "Creature\SUIKart\SUIKartTread.blp", "body": {"base64": base64.b64encode(tread).decode("ascii")}},
        dbc("CreatureModelData", KART_MODEL_ID, 1471, {"2": KART_MODEL_PATH.replace(".m2", ".mdx")}),
        dbc("CreatureDisplayInfo", KART_DISPLAY_ID, 10318, {"1": KART_MODEL_ID}),
        row("creature_display_info_addon", {"display_id": KART_DISPLAY_ID, "build": 0, "bounding_radius": 0.6,
                                              "combat_reach": 1.5, "speed_walk": 4, "speed_run": 4.28571,
                                              "gender": 2, "display_id_other_gender": 0}),
        row("creature_template", t),
    ]


# -- public Real Portals -------------------------------------------------------------------------

def portal_items(course, teleport, go_template):
    items = []
    legs = course["legs"]
    for i, leg in enumerate(legs):
        p = leg.get("portal")
        if not p:
            continue
        dest = legs[p["to"]]
        ax, ay, az, ao = dest["arrive"]
        az = (az if az else leg_z(dest, ax, ay)) + 0.5
        pz = p.get("z")
        if pz is None:
            pz = leg_z(leg, p["x"], p["y"])
        spell = PORTAL_SPELL_BASE + i
        entry = PORTAL_TEMPLATE_BASE + i
        guid = PORTAL_GUID_BASE + i
        name = p.get("name") or f"Portal to {dest['name']}"
        t = dict(teleport)
        t.update({"entry": spell, "build": 5875, "name": f"Kart Portal: {dest['name']}"})
        items.append(row("spell_template", t))
        items.append(dbc("Spell", spell, PORTAL_SOURCE_SPELL, {str(DBC_NAME): t["name"]}))
        items.append(row("spell_target_position", {
            "id": spell, "target_map": dest["map"], "target_position_x": ax, "target_position_y": ay,
            "target_position_z": round(az, 2), "target_orientation": ao, "build_min": 0, "build_max": 5875}))
        g = dict(go_template)
        g.update({"entry": entry, "patch": 0, "name": name, "faction": 35,
                  "data0": spell, "data1": 0, "data2": 0, "data3": 1, "data4": 1})
        items.append(row("gameobject_template", g))
        o = float(p.get("o", 0.0))
        items.append(row("gameobject", {
            "guid": guid, "id": entry, "map": leg["map"], "position_x": p["x"], "position_y": p["y"],
            "position_z": round(pz, 2), "orientation": o, "rotation0": 0, "rotation1": 0,
            "rotation2": round(math.sin(o / 2), 6), "rotation3": round(math.cos(o / 2), 6),
            "spawntimesecsmin": 0, "spawntimesecsmax": 0, "animprogress": 100, "state": 1, "spawn_flags": 0,
            "visibility_mod": 0, "patch_min": 0, "patch_max": 10}))
    return items


# -- laid track ----------------------------------------------------------------------------------

def track_items(course):
    """Laid track: a leg's "ramp" is a World Builder graded path (doc kind "path") - the ground takes the path's
    height within half the width and its short falloff makes the lip a kart jumps off."""
    items = []
    for leg in course["legs"]:
        r = leg.get("ramp")
        if r:
            items.append({"kind": "path", "key": r["name"], "body": {
                "map": leg["map"], "points": r["points"], "width": r["width"], "falloff": r["falloff"], "clear": True}})
        # A cleared lane: props (trees, roots, boulders) standing in the racing line are removed and the ground
        # stays exactly as it is ("grade": false) - `kart-course.py props` lists them (a kart stops dead on a trunk).
        for lane in leg.get("lanes", []):
            route = lane["points"] if "points" in lane else leg["route"][lane["from"]:lane["to"] + 1]
            pts = []
            for k in range(len(route) - 1):
                (ax, ay), (bx, by) = route[k][:2], route[k + 1][:2]
                n = max(1, int(math.dist((ax, ay), (bx, by)) // 6))
                pts += [(ax + (bx - ax) * t / n, ay + (by - ay) * t / n) for t in range(n)]
            pts.append(tuple(route[-1][:2]))
            items.append({"kind": "path", "key": lane["name"], "body": {
                "map": leg["map"], "points": [[round(x, 1), round(y, 1), round(height(leg["map"], x, y), 2)] for x, y in pts],
                "width": lane.get("width", 8), "falloff": lane.get("falloff", 2), "clear": True, "grade": False}})
    return items


# -- the race course (Core SuiKartingRace.cpp reads it) ------------------------------------------

COURSE_KEY = "azeroth"
TELE_BASE = 7400          # game_tele ids of the course (pack rule: >= 7000)


def box_points(course):
    """Item box rows: four boxes across the road at fractions of each leg's route (leg "boxes": [f, ...])."""
    out = []
    for leg in course["legs"]:
        route = [p[:2] for p in leg["route"]]
        total = length(route)
        for f in leg.get("boxes", [0.4, 0.75]):
            want, walked = total * f, 0.0
            for k in range(len(route) - 1):
                seg = math.dist(route[k], route[k + 1])
                if walked + seg >= want:
                    t = (want - walked) / seg
                    x = route[k][0] + (route[k + 1][0] - route[k][0]) * t
                    y = route[k][1] + (route[k + 1][1] - route[k][1]) * t
                    o = math.atan2(route[k + 1][1] - route[k][1], route[k + 1][0] - route[k][0])
                    spacing = leg.get("boxSpacing", 3.5)
                    for i in range(4):
                        off = (i - 1.5) * spacing
                        out.append((leg, x - math.sin(o) * off, y + math.cos(o) * off, o))
                    break
                walked += seg
    return out


def course_items(course):
    """The race the Core runs (SuiKarting RaceManager) reads its course from these game_tele rows - pack rows, so
    the race exists only while the pack is enabled, and every point is also a `.tele kart:...` for testing:
      kart:<course>:meta:laps=<n>       at the start line
      kart:<course>:grid:<nn>           start slots (orientation = facing)
      kart:<course>:cp:<nn>:r<radius>   checkpoints in lap order; cp 00 is the start/finish line
      kart:<course>:box:<nn>            item boxes (MK64 items, Phase 5)
      kart:<course>:portal:<ll>:<entry> the leg's portal gameobject (bots use it; racers get its destination to prewarm)
      kart:<course>:line:<ll>:<nn>      each leg's racing line (bots drive it), its last point at the leg's portal
    """
    rows, tid = [], TELE_BASE
    start = course["start"]

    def tele(name, mapid, x, y, o=0.0, leg=None):
        nonlocal tid
        z = (leg_z(leg, x, y) if leg is not None else height(mapid, x, y)) + 0.5
        rows.append(row("game_tele", {"id": tid, "position_x": x, "position_y": y, "position_z": round(z, 2),
                                      "orientation": round(o, 4), "map": mapid, "name": f"kart:{COURSE_KEY}:{name}"}))
        tid += 1

    lx, ly = start["line"]
    tele(f"meta:laps={course['laps']}", start["map"], lx, ly, start["facing"])
    for i, (x, y) in enumerate(start["grid"]):
        tele(f"grid:{i:02d}", start["map"], x, y, start["facing"])
    cps = [(start["map"], lx, ly, 45, None)]
    for leg in course["legs"]:
        cps += [(leg["map"], c[0], c[1], c[2] if len(c) > 2 else 45, leg) for c in leg.get("checkpoints", [])
                if math.dist(c[:2], (lx, ly)) > 1]
    for i, (m, x, y, r, leg) in enumerate(cps):
        tele(f"cp:{i:02d}:r{int(r)}", m, x, y, leg=leg)
    for i, (leg, x, y, o) in enumerate(box_points(course)):
        tele(f"box:{i:02d}", leg["map"], round(x, 1), round(y, 1), o, leg=leg)
    for li, leg in enumerate(course["legs"]):
        if leg.get("portal"):
            p = leg["portal"]
            tele(f"portal:{li:02d}:{PORTAL_TEMPLATE_BASE + li}", leg["map"], p["x"], p["y"], p.get("o", 0.0), leg=leg)
        pts = [list(p[:2]) for p in leg["route"]]
        if leg.get("portal"):
            pts.append([leg["portal"]["x"], leg["portal"]["y"]])
        for k, (x, y) in enumerate(pts):
            tele(f"line:{li:02d}:{k:02d}", leg["map"], x, y, leg=leg)
    return rows


# -- the MK64 items (Core SuiKartingRace.cpp item engine) ----------------------------------------
# Effect spells: (id, source, name, spell_template overrides, client Spell.dbc fields). Durations
# (SpellDuration.dbc): 36 = 1 s, 65 = 1.5 s, 7 = 5 s, 165 = 7 s.
EFFECT_SPELLS = [
    (38201, 7036, "Kart Boost", {"durationIndex": 65, "effectImplicitTargetA1": 1}, {30: 65, 82: 1}),
    (38202, 7084, "Spun Out", {"durationIndex": 36, "castingTimeIndex": 1, "effectApplyAuraName1": 12, "effectImplicitTargetA1": 1},
     {30: 36, 18: 1, 91: 12, 82: 1}),
    (38203, 7084, "Tumble", {"durationIndex": 65, "castingTimeIndex": 1, "effectApplyAuraName1": 12, "effectImplicitTargetA1": 1,
                             "spellVisual1": 3819}, {30: 65, 18: 1, 91: 12, 82: 1, 115: 3819}),
    (38204, 22580, "Star Power", {"durationIndex": 165, "effectApplyAuraName1": 31, "effectBasePoints1": 34}, {30: 165, 91: 31, 76: 34}),
    (38205, 13003, "Shrunk", {"durationIndex": 7, "effectImplicitTargetA1": 1, "effectApplyAuraName1": 61, "effectBasePoints1": -51,
                              "effect2": 6, "effectApplyAuraName2": 33, "effectBasePoints2": -41, "effectImplicitTargetA2": 1},
     {30: 7, 82: 1, 91: 61, 76: -51 & 0xFFFFFFFF, 62: 6, 92: 33, 77: -41 & 0xFFFFFFFF, 83: 1}),
    (38206, 3680, "Boo", {"durationIndex": 7, "auraInterruptFlags": 0}, {30: 7}),
]
# World objects: gameobjects (item box, banana, fake box) and shell creatures (source creature, display, scale).
# The fake box is the Berserker rune: nearly the item box (the Speed rune) - MK64's tell, WoW's look.
ITEM_GOS = [(7100110, "Item Box", 5931, 1.4), (7100111, "Banana", 367, 2.5), (7100112, "Item Box", 5995, 1.4)]
ITEM_GO_SOURCE = 179871                     # the battleground Speed Buff rune (its display spins and glows)
SHELLS = [(7100010, "Green Shell", 16547, 16259, 0.6), (7100011, "Red Shell", 14632, 14660, 0.3),
          (7100012, "Spiny Shell", 14629, 14657, 0.35)]


def item_items(course):
    items = []
    for sid, source, name, over, dbc_fields in EFFECT_SPELLS:
        r = typed(box_rows(f"SELECT * FROM spell_template WHERE entry={source} ORDER BY build DESC LIMIT 1")[0])
        r.update({"entry": sid, "build": 5875, "name": name, "nameSubtext": "", "description": "", "auraDescription": name})
        r.update(over)
        items.append(row("spell_template", r))
        fields = {str(DBC_NAME): name}
        fields.update({str(k): v for k, v in dbc_fields.items()})
        items.append(dbc("Spell", sid, source, fields))
    g = typed(box_rows(f"SELECT * FROM gameobject_template WHERE entry={ITEM_GO_SOURCE}")[0])
    for entry, name, display, size in ITEM_GOS:
        t = dict(g)
        t.update({"entry": entry, "patch": 0, "type": 5, "displayId": display, "name": name, "faction": 35,
                  "flags": 16, "size": size, **{f"data{i}": 0 for i in range(24)}})
        items.append(row("gameobject_template", t))
    for entry, name, source, display, scale in SHELLS:
        t = typed(box_rows(f"SELECT * FROM creature_template WHERE entry={source} ORDER BY patch DESC LIMIT 1")[0])
        t.update({"entry": entry, "patch": 0, "name": name, "subname": "", "display_id1": display, "display_id2": 0,
                  "display_id3": 0, "display_id4": 0, "display_scale1": scale, "display_probability1": 100,
                  "display_total_probability": 100, "faction": 35, "level_min": 1, "level_max": 1, "npc_flags": 0,
                  "gossip_menu_id": 0, "ai_name": "", "script_name": "", "loot_id": 0, "skinning_loot_id": 0,
                  "pickpocket_loot_id": 0, "gold_min": 0, "gold_max": 0, "inhabit_type": 3, "movement_type": 0})
        items.append(row("creature_template", t))
    return items


# -- the race marshal ----------------------------------------------------------------------------

MARSHAL_ENTRY = 7_100_000          # creature_template / npc_text / broadcast_text
MARSHAL_GUID = 1_700_000
MARSHAL_SOURCE = 4630              # Pozzik, the raceway's goblin mechanic (display 7199)


def marshal_items(course):
    """The race marshal: talk to her for a kart, to join the next race, or to start one now with racer bots
    (Core SuiKartingRace.cpp, script npc_sui_kart_marshal). She stands by the start line."""
    m = course["marshal"]
    t = typed(box_rows(f"SELECT * FROM creature_template WHERE entry={MARSHAL_SOURCE} ORDER BY patch DESC LIMIT 1")[0])
    t.update({"entry": MARSHAL_ENTRY, "patch": 0, "name": m["name"], "subname": m["title"], "npc_flags": 1,
              "gossip_menu_id": 0, "faction": 35, "script_name": "npc_sui_kart_marshal", "ai_name": ""})
    text = m["greeting"]
    z = height(course["start"]["map"], m["x"], m["y"])
    return [
        row("creature_template", t),
        row("broadcast_text", {"entry": MARSHAL_ENTRY, "male_text": text, "female_text": text, "chat_type": 0}),
        row("npc_text", {"ID": MARSHAL_ENTRY, "BroadcastTextID0": MARSHAL_ENTRY, "Probability0": 1}),
        row("creature", {"guid": MARSHAL_GUID, "id": MARSHAL_ENTRY, "map": course["start"]["map"],
                         "position_x": m["x"], "position_y": m["y"], "position_z": round(z, 2), "orientation": m["o"],
                         "spawntimesecsmin": 300, "spawntimesecsmax": 300, "wander_distance": 0, "health_percent": 100,
                         "mana_percent": 100, "movement_type": 0, "spawn_flags": 0, "visibility_mod": 0,
                         "patch_min": 0, "patch_max": 10}),
    ]


# -- posting -------------------------------------------------------------------------------------

def post(path, body):
    req = urllib.request.Request(f"{WEB}{path}", data=json.dumps(body).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    return json.load(urllib.request.urlopen(req, timeout=300))


def pack_id():
    packs = json.load(urllib.request.urlopen(f"{WEB}/WorldPacks/Packs", timeout=60))["packs"]
    for p in packs:
        if p["packKey"] == PACK_KEY:
            return p["id"]
    r = post("/WorldPacks/CreatePack", {"key": PACK_KEY, "name": "WoW Karting",
                                         "description": "Racer karts, public Real Portals and the Azeroth Circuit (shared_docs/WOW_KARTING.md)",
                                         "operator": "gen-karting"})
    return r["pack"]["id"] if isinstance(r.get("pack"), dict) else r["pack"]


def main():
    out = sys.argv[1]
    os.makedirs(out, exist_ok=True)
    course = json.load(open(os.path.join(HERE, "course.json"), encoding="utf-8"))
    mount = typed(box_rows(f"SELECT * FROM spell_template WHERE entry={MOUNT_SOURCE} ORDER BY build DESC LIMIT 1")[0])
    teleport = typed(box_rows(f"SELECT * FROM spell_template WHERE entry={PORTAL_SOURCE_SPELL} ORDER BY build DESC LIMIT 1")[0])
    go_template = typed(box_rows(f"SELECT * FROM gameobject_template WHERE entry={PORTAL_SOURCE_GO}")[0])
    batches = {"kartmodel": kart_model_items(), "karts": kart_items(mount), "portals": portal_items(course, teleport, go_template),
               "track": track_items(course), "course": course_items(course), "marshal": marshal_items(course),
               "items": item_items(course)}
    for name, items in batches.items():
        with open(os.path.join(out, f"karting-{name}.json"), "w", encoding="utf-8") as f:
            json.dump(items, f, indent=1)
        print(f"{name}: {len(items)} item(s)")
    if "--post" in sys.argv:
        pid = pack_id()
        written = set()
        for name, items in batches.items():
            r = post("/WorldPacks/Content", {"packId": pid, "label": f"karting {name}", "items": items, "operator": "gen-karting"})
            print(f"posted {name} to pack {pid}: success={r.get('success')} {r.get('error', '')}")
            written |= {(k["kind"], k["key"]) for k in r.get("keys", [])}
        # The pack holds exactly what the course generates: a doc the course no longer produces (a moved portal's
        # old destination row - spell_target_position is keyed by (id, map)) is deleted, not left to conflict.
        docs = json.load(urllib.request.urlopen(f"{WEB}/WorldPacks/Docs?packId={pid}", timeout=60))["docs"]
        stale = [{"kind": d["kind"], "key": d["docKey"], "body": None} for d in docs if (d["kind"], d["docKey"]) not in written]
        if stale:
            r = post("/WorldPacks/Content", {"packId": pid, "label": "karting: remove stale docs", "items": stale, "operator": "gen-karting"})
            print(f"removed {len(stale)} stale doc(s): {[s['kind'] + ' ' + s['key'] for s in stale]} success={r.get('success')}")


if __name__ == "__main__":
    main()
